self.character_id = 'Moonlight_Global'
self.num_resurrect = 3
self.gap_resurrect = 0
self.equip_basic = 3
self.statue_basic = 1
self.friend_basic = 2
self.water_basic= False
self.gap_economic= 600
self.team_accept = False
self.team_add = False

self.enable_auction = True
self.gap_auction = 40
self.auction_item = '¥ì·æ'

self.enable_daily = True
self.enable_reward = True
self.enable_coinstore = True
self.hour_daily = 5
self.min_daily = 10

self.enable_hunt = True
self.hour_guild = 9
self.min_guild = 55
self.x_guild = 0.835
self.y_guild = 0.308
self.equip_guild = 1
self.statue_guild = 1
self.friend_guild = 5
self.leave_guild = True

self.enable_raid = True
self.early_raid = 2
self.level_raid = 300
self.gap_resurrect_raid = 0
self.ticket_raid = True
self.raid1 = False
self.raid2 = False
self.raid3 = True
self.raid4 = True
self.raid5 = True
self.raid6 = True
self.raid7 = True
self.raid8 = True
self.equip_raid = 3
self.statue_raid = 1
self.friend_raid = 2
self.water_raid = True
self.sp_raid = True

self.enable_pvp = True
self.hour_start_pvp = 19
self.min_start_pvp = 30
self.hour_end_pvp = 20
self.min_end_pvp = 50
self.until_reward = False
self.equip_pvp = 2
self.statue_pvp = 2
self.friend_pvp = 9
self.sp_pvp = True
self.ep_pvp = True

self.t_boss = 1652238047.7453818
self.t_auction = 1676201443.051143
self.d_daily = 2023043
self.d_pvp = 2023025
self.d_hunt = 2023043
self.d_reward = 2023043
self.d_coinstore = 2023043
